/*
=========================================================================
				 SECTION 2: Pizza Size Performance
=========================================================================
*/


-- 7. What is the revenue generated by each pizza size?

select
	size,
	round(sum(price*quantity)/1000,0) as total_revenue_in_thousands
from order_details od
join orders o
on od.order_id = o.order_id
join pizzas p
on p.pizza_id = od.pizza_id
group by size
order by total_revenue_in_thousands desc;


-- 'L' dominates the sales significantly and 'XXL' is the least preferred



-- 8. Which pizza in each size brought in the highest revenue?

with cte as (
select
	size,
	name as pizza_name,
	size as pizza_size,
	round(sum(price*quantity),2) as revenue
from order_details od
join orders o
on od.order_id = o.order_id
join pizzas p
on p.pizza_id = od.pizza_id
join pizza_types pt
on pt.pizza_type_id = p.pizza_type_id
group by size, name
),

cte2 as (
select 
	*,
	rank() over(partition by pizza_size order by revenue desc) as pizza_rnk
from cte
)

select 
	pizza_name,
	pizza_size,
	revenue
from cte2
where pizza_rnk = 1;


