/*
=========================================================================
				 SECTION 3: Pizza Category Performance
=========================================================================
*/

-- 9. What is the total revenue generated by each pizza category?

select 
	category,
	round((sum(price*quantity) / 1000), 0) as total_revenue_in_thousands
from order_details od
join orders o
on od.order_id = o.order_id
join pizzas p
on p.pizza_id = od.pizza_id
join pizza_types pt
on pt.pizza_type_id = p.pizza_type_id
group by category
order by round(sum(price), 2) desc;

-- All the categories have more or less equal sharing in revenue


-- 10. Which pizza in each category brought in the highest revenue?

with cte as (
select
	category,
	name as pizza_name,
	size as pizza_size,
	round(sum(price*quantity),2) as revenue
from order_details od
join orders o
on od.order_id = o.order_id
join pizzas p
on p.pizza_id = od.pizza_id
join pizza_types pt
on pt.pizza_type_id = p.pizza_type_id
group by category, size, name
),

cte2 as (
select 
	*,
	rank() over(partition by category order by revenue desc) as pizza_rnk
from cte
)

select 
	pizza_name,
	pizza_size,
	category,
	revenue,
	pizza_rnk
from cte2
where pizza_rnk = 1;
